name: CI

on:
  push:
    branches:
      - staging
    tags:
      - "v*"
  pull_request:
    branches:
      - staging

permissions:
  contents: write

jobs:

  # =========================
  # LINT (ruff)
  # =========================
  lint:
    name: Ruff check & format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install ruff
        run: uv sync

      - name: Ruff check
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --check .

  # =========================
  # BUILD EXE FILE
  # =========================
  build-exe:
    name: Build Windows executable
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: Download mkcert
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path bin
          Invoke-WebRequest `
            -Uri "https://dl.filippo.io/mkcert/latest?for=windows/amd64" `
            -OutFile "bin/mkcert.exe"

      - name: Build EXE
        run: |
          uv run pyinstaller MaieuticAnalyzer.spec

      - name: Rename executable
        shell: pwsh
        run: |
          $version = "${env:GITHUB_REF_NAME}" -replace "^v", ""
          Rename-Item `
            "dist\MaieuticAnalyzer.exe" `
            "MaieuticAnalyzer_$version.exe"

      - name: Create Release + Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: MaieuticAnalyzer ${{ env.GITHUB_REF_NAME }}
          files: dist/MaieuticAnalyzer_*.exe
